"""empty message

Revision ID: 326100d8fa44
Revises: 6a37ea0d0335
Create Date: 2019-03-19 10:22:22.333115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326100d8fa44'
down_revision = '6a37ea0d0335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('usage_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(), nullable=False),
    sa.Column('time_to_prompt', sa.DateTime(), nullable=True),
    sa.Column('ending_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['user.chat_id'], ),
    sa.ForeignKeyConstraint(['usage_id'], ['usage.id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'usage_id'),
    sa.UniqueConstraint('usage_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt')
    # ### end Alembic commands ###
