"""empty message

Revision ID: 5851f652fa66
Revises: 4d46f77a98c2
Create Date: 2019-03-19 23:17:54.565616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5851f652fa66'
down_revision = '4d46f77a98c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('machine_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'sensor', 'machine', ['machine_id'], ['machine_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor', type_='foreignkey')
    op.drop_column('sensor', 'machine_id')
    # ### end Alembic commands ###
