"""empty message

Revision ID: 68ed4490a59c
Revises: 326100d8fa44
Create Date: 2019-03-19 10:23:12.910207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ed4490a59c'
down_revision = '326100d8fa44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(), nullable=False),
    sa.Column('sensor_type', sa.String(), nullable=False),
    sa.Column('deployment_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sensor_id')
    )
    op.create_table('motion_sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('sensor_figure', sa.Integer(), nullable=False),
    sa.Column('status_conclusion', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.sensor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vibration_sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('sensor_figure', sa.Integer(), nullable=False),
    sa.Column('status_conclusion', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.sensor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vibration_sensor_data')
    op.drop_table('motion_sensor_data')
    op.drop_table('sensor')
    # ### end Alembic commands ###
