"""empty message

Revision ID: 745132a789c7
Revises: 
Create Date: 2019-03-19 10:16:57.348958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745132a789c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('modified_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
